version: "3.3"

services:
  aws-step-functions:
    container_name: aws-step-functions
    image: amazon/aws-stepfunctions-local
    ports:
      - 8083:8083
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - WAIT_TIME_SCALE=15
      - LAMBDA_ENDPOINT=http://127.0.0.1:3001
      - BATCH_ENDPOINT=
      - DYNAMODB_ENDPOINT=
      - ECS_ENDPOINT=
      - GLUE_ENDPOINT=
      - SAGE_MAKER_ENDPOINT=
      - SQS_ENDPOINT=
      - SNS_ENDPOINT=
      - STEP_FUNCTIONS_ENDPOINT=http://127.0.0.1:8083
    network_mode: host
