AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple SAM template for experimenting debug SF workflow

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  HostDockerInternal:
    Type: String
    Description: Docker host ip address. Default works for Mac and Windows.
    Default: "host.docker.internal"

Resources:
  HelloWorldLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/hello-world
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          HOST_DOCKER_INTERNAL: !Ref HostDockerInternal

  TypescriptNodeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/ts-node/
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          HOST_DOCKER_INTERNAL: !Ref HostDockerInternal

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldLambdaFunction.Arn

  TypescriptNodeLambdaFunction:
    Description: "Typescript tests lambda function"
    Value: !GetAtt TypescriptNodeLambdaFunction.Arn

  GreatmindsLocalIamRole:
    Description: "Implicit IAM Role created for Lambda functions"
    Value: !GetAtt GreatmindsFunctionRole.Arn
